baseURL = "https://altaweelmustafa.github.io/docs/"
languageCode = "en-us"
title = "Docs"
theme = "sollike"

[params]
  subtitle = "Courses/Books/APIs documentation"
  footer = "© 2026 Mustafa and Samaa"

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    codeFences  = true
    guessSyntax = true
    noClasses   = false
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Courses"
  url = "/courses"
  weight = 1

[[menu.main]]
  name = "Books"
  url = "/books"
  weight = 2

[[menu.main]]
  name = "APIs"
  url = "/apis"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
